USE ROOT;

/**Tabelas de infraestrutura**/

CREATE TABLE TB_PERFIL(
ID_PERFIL smallint unsigned not null auto_increment, 
NM_PERFIL VARCHAR(30) NOT NULL,
CONSTRAINT PK_PERFIL primary key (ID_PERFIL));

CREATE INDEX IN_TB_PERFIL_01 ON TB_PERFIL(ID_PERFIL);

CREATE TABLE TB_USUARIO(
ID_USUARIO smallint unsigned not null auto_increment, 
NM_USUARIO VARCHAR(200) not null, 
DS_SENHA VARCHAR(200) NOT NULL,
MAIL_USUARIO VARCHAR(200) not null,
IN_ATIVO VARCHAR(1) NOT NULL,
ID_PERFIL smallint unsigned NOT NULL,
CONSTRAINT PK_USUARIO primary key (ID_USUARIO),
CONSTRAINT FK_TB_PERFIL FOREIGN KEY (ID_PERFIL) REFERENCES TB_PERFIL(ID_PERFIL));

CREATE TABLE TB_PARAMETRO(
ID_PARAMETRO smallint unsigned not null auto_increment, 
NM_PARAMETRO VARCHAR(200) not null, 
VAL_PARAMETRO VARCHAR(200) not null, 
IN_ATIVO VARCHAR(1) NOT NULL,
CONSTRAINT PK_PARAMETRO PRIMARY KEY (ID_PARAMETRO));

CREATE TABLE TB_TOKEN_SEGURANCA(
ID_TOKEN_SEGURANCA smallint unsigned not null auto_increment, 
NM_TOKEN VARCHAR(30) NOT NULL,
DS_SECRET_KEY VARCHAR(200) NOT NULL,
IN_ATIVO VARCHAR(1) NOT NULL,
CONSTRAINT PK_TOKEN_SEGURANCA primary key(ID_TOKEN_SEGURANCA));

/**Tabelas de negócio8**/



